name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v7

      - name: Build LidGrace
        run: |
          chmod +x Scripts/*.sh
          ./Scripts/build.sh
